### ISSUE TITLE
Having a hard time understanding this

### ISSUE THREAD

**Issue by PainDeMie64** [donadigo/TMInterfaceClientPython#1]
Hello! Im a java programmer and never really went into python. From what I see, it seems to be an api to use on our own to interact with a TMInterface instace. Is that what it is? If so, I don't understand how you would 'connect' to the instance, and then do more stuff. Would this allow me, for example, to create my own brute force script? Any help would be appreciated ;)

Thanks for your time and making this beautiful tool

**Comment by donadigo** [comment]
Yes, this is an example implementation of a client that connects to a TMInterface instance. The instance always launches a "server" which is simply a memory mapped file that gets open by the Python client and then messages are sent between two processes. The API indeed allows you for writing your own bruteforce algorithms and controlling the game state in general. It's quite a work in progress, but it is workable. There is also a WIP documentation here: https://donadigo.github.io/tminterface-server

**Comment by Skycrafter-dev** [comment]
I guess I have to learn python now :D. Thanks for the answer. I'm having trouble even figuring out how to make simulations with custom inputs while a replay is being validated 😅. I'd love a more detailed wiki, but I know you're very busy irl. Maybe just basic code examples for brute forcing from the tminterface default one, would be very useful in the readme file.
