### ISSUE TITLE
Event into steer value?

### ISSUE THREAD

**Issue by PainDeMie64** [donadigo/TMInterfaceClientPython#2]
Hello! Sorry to bother, but I'm stuck on something very simple and I hope you'll be able to help me. When I retrieve the `input_steer_state`, it's an `Event ` class. How do I turn it into a steer value [-65536:65536] ? I saw that in your public repo for tminterface, you used a function called `eventToSteerValue` from the `GameEventBuffer` class. Only... I don't know how this function works as it's not public, so would you mind helping me with that? Thanks :D

**Comment by donadigo** [comment]
Hey! If your simulation state is coming from `on_run_step`, you don't need to convert the value, simply access `event.data`, if you're getting the simulation state from `on_simulation_step`, you should do `event.analog_value` which is defined here: https://github.com/donadigo/TMInterfaceClientPython/blob/master/tminterface/structs.py#L39. This should give you the desired value.

This might change in the future.

**Comment by Skycrafter-dev** [comment]
Thanks for the answer! I'm doing it from `on_simulation_step`. I had tried `event.analog_value` in the past, and I tried again, but the analog value is always 0. I checked that I correctly updated the sim state everytime and I did. Where could this come from?

**Comment by donadigo** [comment]
By any chance, is the replay you're doing it on a keyboard replay? `input_steer_state` applies only for analog steer, and `input_left_state` and `input_right_state` indicate left/right keys. You can check this by extracting the inputs of a replay and seeing what commands it contains.

**Comment by Skycrafter-dev** [comment]
Oh thanks! This is exactly what happened 😅 Sorry for bothering but I guess it'll help the newcomers
