### ISSUE TITLE
Crosscheck quat_to_ypw implementation

### ISSUE THREAD

**Issue by donadigo** [donadigo/TMInterfaceClientPython#5]
From Adrien: "if `abs(t0 - 0.5) < 0.00001 or t0 - 0.5 >= 0:` on line 62 but i think it should rather be something like `if abs(t0) - 0.5 < 0.00001 or abs(t0) - 0.5 >= 0:` because `if t0 is -0.5`, the asin line 67 will throw an error (-inf value).

**Comment by adrien-obrecht** [comment]
Sorry for not making a pull request. I checked inside the game and there is one more check for t0=-0.5 (here only t0=0.5 is made)
Adding this line 60 treats the other case 
if abs(t0 + 0.5) < 0.00001 or t0 + 0.5 <= 0:
    yaw = math.atan2(quat[1], quat[0])
    return np.array([yaw * 2, -1.57079637, 0])

**Comment by donadigo** [comment]
Fixed as of https://github.com/donadigo/TMInterfaceClientPython/commit/9d03a73adc54903085505a6000ef3f32c3ccdeb7, thanks.
